name = "SymbolicTracingUtils"
uuid = "77ddf47f-b2ab-4ded-95ee-54f4fa148129"
authors = ["lassepe <lasse.peters@mailbox.org>"]
version = "0.1.0"

[weakdeps]
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
FastDifferentiationExt = "Contour"
SymbolicsExt = "FastDifferentiation"

[compat]
julia = "1.10"
Symbolics = "4,5"
FastDifferentiation = "0.3"
