name = "SymbolicTracingUtils"
uuid = "77ddf47f-b2ab-4ded-95ee-54f4fa148129"
authors = ["lassepe <lasse.peters@mailbox.org>"]
version = "0.1.2"

[deps]
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
FastDifferentiation = "0.3,0.4"
SparseArrays = "1.10"
Symbolics = "4,5,6"
julia = "1.10"
